logging:
  level:
    root: INFO
    com.ai.sin: DEBUG
    org.springframework: INFO
  file: logs/app-sin.log

# default to dev
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    # this is default url that spring-boot will load , if you change, those schemal.sql and data.sql in classpath will not work
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    com.ai.sin: DEBUG
    org.springframework: INFO

---
spring:
  profiles: sit

logging:
  level:
    root: INFO
    com.ai.sin: INFO
    org.springframework: INFO

---
spring:
  profiles: uat

logging:
  level:
    root: WARN
    com.ai.sin: INFO
    org.springframework: WARN

---
spring:
  profiles: pt
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    # this is default url that spring-boot will load , if you change, those schemal.sql and data.sql in classpath will not work
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    com.ai.sin: INFO
    org.springframework: INFO


---
spring:
  profiles: prod

logging:
  level:
    root: WARN
    com.ai.sin: INFO
    org.springframework: WARN

