-- basic tables starts
create table client(
    id bigint generated by default as identity(start with 1) primary key,
    name varchar(32) not null,
    risk int(2)
);

create table product(
    id bigint generated by default as identity(start with 1) primary key,
    name varchar(32) not null,
    risk int(2),
    investment int(2)
);